/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f446xx.h"
#include "reg_util.h"
#include "bsp_lcd.h"

#define RGB888(r,g,b)		(((r << 16) | (g << 8)) | b)

#define VIOLET   	RGB888(148,0,211)
#define INDIGO   	RGB888(75,0,130)
#define BLUE   		RGB888(0,0,255)
#define GREEN   	RGB888(0,255,0)
#define YELLOW   	RGB888(255,255,0)
#define ORANGE   	RGB888(255,127,0)
#define RED   		RGB888(255,0,0)
#define WHITE   	RGB888(255,255,255)
#define BLACK		RGB888(0,0,0)

void system_clock_setup(void);

int main(void)
{
	uint32_t x_start,x_width,y_start,y_height;

	system_clock_setup();
	bsp_lcd_init();
	bsp_lcd_set_background_color(RED);
	for (x_start = 0; x_start < 20; x_start++) {
		delay_50ms();
	}

	bsp_lcd_set_background_color(BLACK);
	for (x_start = 0; x_start < 20; x_start++) {
		delay_50ms();
	}

#if(BSP_LCD_ORIENTATION == LANDSCAPE)
	x_start = 0;
	y_start = 0;
	x_width = 320;
	y_height = 34;
#elif(BSP_LCD_ORIENTATION == PORTRAIT)
	x_start = 0;
	y_start = 0;
	x_width = 240;
	y_height = 45;
#endif
	bsp_lcd_fill_rect(VIOLET, x_start, x_width, y_height*0, y_height);
	bsp_lcd_fill_rect(INDIGO, x_start, x_width, y_height*1, y_height);
	bsp_lcd_fill_rect(BLUE,   x_start, x_width, y_height*2, y_height);
	bsp_lcd_fill_rect(GREEN,  x_start, x_width, y_height*3, y_height);
	bsp_lcd_fill_rect(YELLOW, x_start, x_width, y_height*4, y_height);
	bsp_lcd_fill_rect(ORANGE, x_start, x_width, y_height*5, y_height);
	bsp_lcd_fill_rect(RED, 	  x_start, x_width, y_height*6, y_height);
	//bsp_lcd_fill_rect(YELLOW, x_start, x_width, y_height*4, y_height);

    /* Loop forever */
	for(;;);
}


void system_clock_setup(void)
{
	RCC_TypeDef *pRCC = RCC;
	FLASH_TypeDef *pFlash = FLASH;
	PWR_TypeDef *pPWR = PWR;

	REG_SET_BIT(pFlash->ACR, FLASH_ACR_PRFTEN_Pos);
	REG_SET_BIT(pFlash->ACR, FLASH_ACR_ICEN_Pos);
	REG_SET_BIT(pFlash->ACR, FLASH_ACR_DCEN_Pos);
	REG_SET_VAL(pFlash->ACR, 0x5U, 0xFU, FLASH_ACR_LATENCY_Pos);
	while (REG_READ_VAL(pFlash->ACR, 0x7U, FLASH_ACR_LATENCY_Pos) != 0x5U);

	// Overdrive settings to ensure 180MHz is reached
	// Can only be changed when PLL off and the HSI/HSE is clk src
	REG_SET_BIT(pRCC->APB1ENR, RCC_APB1ENR_PWREN_Pos);
	REG_SET_VAL(pPWR->CR, 0x3, 0x3, PWR_CR_VOS_Pos);  // VOS = 0b11
	REG_SET_BIT(pPWR->CR, PWR_CR_ODEN_Pos);
	while (!REG_READ_BIT(pPWR->CSR, PWR_CSR_ODRDY_Pos)); // wait for ready

	// Select HSI or HSE as system clock.
	// Set BYPASS MODE and HSEON
	REG_SET_BIT(pRCC->CR, RCC_CR_HSEBYP_Pos);
	REG_SET_BIT(pRCC->CR, RCC_CR_HSEON_Pos);
	while (!REG_READ_BIT(pRCC->CR, RCC_CR_HSERDY_Pos));

	// Configure RCC_PLLCFGR register
	REG_SET_VAL(pRCC->PLLCFGR, 0x4U, 0x3FU, RCC_PLLCFGR_PLLM_Pos);
	REG_SET_VAL(pRCC->PLLCFGR, 180U, 0x1FFU, RCC_PLLCFGR_PLLN_Pos);
	REG_SET_VAL(pRCC->PLLCFGR, 0x0U, 0x3FU, RCC_PLLCFGR_PLLP_Pos);
	REG_SET_VAL(pRCC->PLLCFGR, 0x0U, 0x3FU, RCC_PLLCFGR_PLLR_Pos);
	REG_SET_BIT(pRCC->PLLCFGR, RCC_PLLCFGR_PLLSRC_Pos);

	// set PLLON bit of RCC_CR register.
	REG_SET_BIT(pRCC->CR, RCC_CR_PLLON_Pos);

	// Wait for PLL lock.
	while (!REG_READ_BIT(pRCC->CR, RCC_CR_PLLRDY_Pos));


	REG_SET_VAL(pRCC->CFGR, 0x0, 0xFU, RCC_CFGR_HPRE_Pos);
	REG_SET_VAL(pRCC->CFGR, 0x5U, 0x7U, RCC_CFGR_PPRE1_Pos);
	REG_SET_VAL(pRCC->CFGR, 0x4U, 0x7U, RCC_CFGR_PPRE2_Pos);


	// Switch the system clock to the PLL
	REG_SET_VAL(pRCC->CFGR, 0x2U, 0x3U, RCC_CFGR_SW_Pos);
	while (!(REG_READ_VAL(pRCC->CFGR, 0x3U, RCC_CFGR_SWS_Pos) == 0x2U));
}
